version: 2

updates:
  - package-ecosystem: npm
    directory: /admin
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: composer
    directory: /api
    schedule:
      interval: weekly
    groups:
      composer-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
