///
/// @Generated by Mockolo
///

import Combine
import Foundation
@testable import kumatomo

final class EngagementRepositoryMock: EngagementRepository {
    init() {}

    private(set) var fetchLikedPostsCallCount = 0
    var fetchLikedPostsHandler: ((Int?, Int?) async throws -> [Post])?
    func fetchLikedPosts(page: Int?, limit: Int?) async throws -> [Post] {
        fetchLikedPostsCallCount += 1
        if let fetchLikedPostsHandler = fetchLikedPostsHandler {
            return try await fetchLikedPostsHandler(page, limit)
        }
        return [Post]()
    }

    private(set) var fetchBookmarkedPostsCallCount = 0
    var fetchBookmarkedPostsHandler: ((Int?, Int?) async throws -> [Post])?
    func fetchBookmarkedPosts(page: Int?, limit: Int?) async throws -> [Post] {
        fetchBookmarkedPostsCallCount += 1
        if let fetchBookmarkedPostsHandler = fetchBookmarkedPostsHandler {
            return try await fetchBookmarkedPostsHandler(page, limit)
        }
        return [Post]()
    }

    private(set) var optimisticToggleLikeCallCount = 0
    var optimisticToggleLikeHandler: ((Int, Bool, Int) async -> (success: Bool, response: (
        isLiked: Bool,
        likeCount: Int
    )?, error: EngagementError?))?
    func optimisticToggleLike(postId: Int, currentState: Bool, currentCount: Int) async -> (success: Bool, response: (
        isLiked: Bool,
        likeCount: Int
    )?, error: EngagementError?) {
        optimisticToggleLikeCallCount += 1
        if let optimisticToggleLikeHandler = optimisticToggleLikeHandler {
            return await optimisticToggleLikeHandler(postId, currentState, currentCount)
        }
        return (false, false nil, nil)
    }

    private(set) var optimisticToggleBookmarkCallCount = 0
    var optimisticToggleBookmarkHandler: ((Int, Bool, Int) async -> (success: Bool, response: (
        isBookmarked: Bool,
        bookmarkCount: Int
    )?, error: EngagementError?))?
    func optimisticToggleBookmark(postId: Int, currentState: Bool, currentCount: Int) async -> (success: Bool, response: (
        isBookmarked: Bool,
        bookmarkCount: Int
    )?, error: EngagementError?) {
        optimisticToggleBookmarkCallCount += 1
        if let optimisticToggleBookmarkHandler = optimisticToggleBookmarkHandler {
            return await optimisticToggleBookmarkHandler(postId, currentState, currentCount)
        }
        return (false, false nil, nil)
    }

    private(set) var toggleLikeCallCount = 0
    var toggleLikeHandler: ((Int) async throws -> (isLiked: Bool, likeCount: Int))?
    func toggleLike(postId: Int) async throws -> (isLiked: Bool, likeCount: Int) {
        toggleLikeCallCount += 1
        if let toggleLikeHandler = toggleLikeHandler {
            return try await toggleLikeHandler(postId)
        }
        return (false, 0)
    }

    private(set) var toggleBookmarkCallCount = 0
    var toggleBookmarkHandler: ((Int) async throws -> (isBookmarked: Bool, bookmarkCount: Int))?
    func toggleBookmark(postId: Int) async throws -> (isBookmarked: Bool, bookmarkCount: Int) {
        toggleBookmarkCallCount += 1
        if let toggleBookmarkHandler = toggleBookmarkHandler {
            return try await toggleBookmarkHandler(postId)
        }
        return (false, 0)
    }
}

final class PostRepositoryMock: PostRepository {
    init() {}

    private(set) var fetchAllPostsCallCount = 0
    var fetchAllPostsHandler: ((Int?, Int?) async throws -> [Post])?
    func fetchAllPosts(page: Int?, limit: Int?) async throws -> [Post] {
        fetchAllPostsCallCount += 1
        if let fetchAllPostsHandler = fetchAllPostsHandler {
            return try await fetchAllPostsHandler(page, limit)
        }
        return [Post]()
    }

    private(set) var fetchUserPostsCallCount = 0
    var fetchUserPostsHandler: ((Int, Int?, Int?) async throws -> [Post])?
    func fetchUserPosts(userId: Int, page: Int?, limit: Int?) async throws -> [Post] {
        fetchUserPostsCallCount += 1
        if let fetchUserPostsHandler = fetchUserPostsHandler {
            return try await fetchUserPostsHandler(userId, page, limit)
        }
        return [Post]()
    }

    private(set) var fetchMunicipalityPostsCallCount = 0
    var fetchMunicipalityPostsHandler: ((String, Int?, Int?) async throws -> [Post])?
    func fetchMunicipalityPosts(municipality: String, page: Int?, limit: Int?) async throws -> [Post] {
        fetchMunicipalityPostsCallCount += 1
        if let fetchMunicipalityPostsHandler = fetchMunicipalityPostsHandler {
            return try await fetchMunicipalityPostsHandler(municipality, page, limit)
        }
        return [Post]()
    }

    private(set) var fetchFollowingPostsCallCount = 0
    var fetchFollowingPostsHandler: ((Int?, Int?) async throws -> [Post])?
    func fetchFollowingPosts(page: Int?, limit: Int?) async throws -> [Post] {
        fetchFollowingPostsCallCount += 1
        if let fetchFollowingPostsHandler = fetchFollowingPostsHandler {
            return try await fetchFollowingPostsHandler(page, limit)
        }
        return [Post]()
    }

    private(set) var createPostCallCount = 0
    var createPostHandler: ((Int, String, String?, [String]) async throws -> Post)?
    func createPost(userId: Int, content: String, imageUrl: String?, tags: [String]) async throws -> Post {
        createPostCallCount += 1
        if let createPostHandler = createPostHandler {
            return try await createPostHandler(userId, content, imageUrl, tags)
        }
        fatalError("createPostHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var createPostWithMultipleImagesCallCount = 0
    var createPostWithMultipleImagesHandler: ((Int, String, [String], [String]) async throws -> Post)?
    func createPostWithMultipleImages(userId: Int, content: String, imageUrls: [String], tags: [String]) async throws -> Post {
        createPostWithMultipleImagesCallCount += 1
        if let createPostWithMultipleImagesHandler = createPostWithMultipleImagesHandler {
            return try await createPostWithMultipleImagesHandler(userId, content, imageUrls, tags)
        }
        fatalError("createPostWithMultipleImagesHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var updatePostCallCount = 0
    var updatePostHandler: ((Int, String, [String]) async throws -> Post)?
    func updatePost(postId: Int, content: String, tags: [String]) async throws -> Post {
        updatePostCallCount += 1
        if let updatePostHandler = updatePostHandler {
            return try await updatePostHandler(postId, content, tags)
        }
        fatalError("updatePostHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var deletePostCallCount = 0
    var deletePostHandler: ((Int) async throws -> Void)?
    func deletePost(postId: Int) async throws {
        deletePostCallCount += 1
        if let deletePostHandler = deletePostHandler {
            try await deletePostHandler(postId)
        }
    }

    private(set) var fetchPostCallCount = 0
    var fetchPostHandler: ((Int) async throws -> Post)?
    func fetchPost(postId: Int) async throws -> Post {
        fetchPostCallCount += 1
        if let fetchPostHandler = fetchPostHandler {
            return try await fetchPostHandler(postId)
        }
        fatalError("fetchPostHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var toggleReactionCallCount = 0
    var toggleReactionHandler: ((Int, ReactionType) async throws -> (reactions: PostReactions, userReaction: ReactionType?))?
    func toggleReaction(postId: Int, reactionType: ReactionType) async throws -> (reactions: PostReactions, userReaction: ReactionType?) {
        toggleReactionCallCount += 1
        if let toggleReactionHandler = toggleReactionHandler {
            return try await toggleReactionHandler(postId, reactionType)
        }
        fatalError("toggleReactionHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var toggleBookmarkCallCount = 0
    var toggleBookmarkHandler: ((Int) async throws -> Bool)?
    func toggleBookmark(postId: Int) async throws -> Bool {
        toggleBookmarkCallCount += 1
        if let toggleBookmarkHandler = toggleBookmarkHandler {
            return try await toggleBookmarkHandler(postId)
        }
        return false
    }

    private(set) var fetchAllPostsWithCacheCallCount = 0
    var fetchAllPostsWithCacheHandler: ((Int, Int, Bool) async throws -> [Post])?
    func fetchAllPostsWithCache(page: Int, limit: Int, useCache: Bool) async throws -> [Post] {
        fetchAllPostsWithCacheCallCount += 1
        if let fetchAllPostsWithCacheHandler = fetchAllPostsWithCacheHandler {
            return try await fetchAllPostsWithCacheHandler(page, limit, useCache)
        }
        return [Post]()
    }

    private(set) var fetchMunicipalityPostsWithCacheCallCount = 0
    var fetchMunicipalityPostsWithCacheHandler: ((String, Int, Int, Bool) async throws -> [Post])?
    func fetchMunicipalityPostsWithCache(municipality: String, page: Int, limit: Int, useCache: Bool) async throws -> [Post] {
        fetchMunicipalityPostsWithCacheCallCount += 1
        if let fetchMunicipalityPostsWithCacheHandler = fetchMunicipalityPostsWithCacheHandler {
            return try await fetchMunicipalityPostsWithCacheHandler(municipality, page, limit, useCache)
        }
        return [Post]()
    }

    private(set) var fetchFollowingPostsWithCacheCallCount = 0
    var fetchFollowingPostsWithCacheHandler: ((Int, Int, Bool) async throws -> [Post])?
    func fetchFollowingPostsWithCache(page: Int, limit: Int, useCache: Bool) async throws -> [Post] {
        fetchFollowingPostsWithCacheCallCount += 1
        if let fetchFollowingPostsWithCacheHandler = fetchFollowingPostsWithCacheHandler {
            return try await fetchFollowingPostsWithCacheHandler(page, limit, useCache)
        }
        return [Post]()
    }
}

final class AuthRepositoryMock: AuthRepository {
    init() {}
    init(isAuthenticated: Bool = false, currentUser: User? = nil) {
        self.isAuthenticated = isAuthenticated
        self.currentUser = currentUser
    }

    var isAuthenticated: Bool = false

    var currentUser: User?

    var isAuthenticatedPublisher: AnyPublisher<Bool, Never> { return isAuthenticatedPublisherSubject.eraseToAnyPublisher() }
    private(set) var isAuthenticatedPublisherSubject = PassthroughSubject<Bool, Never>()

    var currentUserPublisher: AnyPublisher<User?, Never> { return currentUserPublisherSubject.eraseToAnyPublisher() }
    private(set) var currentUserPublisherSubject = PassthroughSubject<User?, Never>()

    private(set) var signInCallCount = 0
    var signInHandler: ((String, String) async throws -> Void)?
    func signIn(withEmail email: String, password: String) async throws {
        signInCallCount += 1
        if let signInHandler = signInHandler {
            try await signInHandler(email, password)
        }
    }

    private(set) var signOutCallCount = 0
    var signOutHandler: (() async throws -> Void)?
    func signOut() async throws {
        signOutCallCount += 1
        if let signOutHandler = signOutHandler {
            try await signOutHandler()
        }
    }

    private(set) var createUserCallCount = 0
    var createUserHandler: ((String, String) async throws -> Void)?
    func createUser(withEmail email: String, password: String) async throws {
        createUserCallCount += 1
        if let createUserHandler = createUserHandler {
            try await createUserHandler(email, password)
        }
    }

    private(set) var updateUserCallCount = 0
    var updateUserHandler: ((String?, String?, String?, String?, Date?, Bool?) async throws -> Void)?
    func updateUser(withName name: String?, profileImageURL: String?, bio: String?, location: String?, birthday: Date?, hasCompletedSetup: Bool?) async throws {
        updateUserCallCount += 1
        if let updateUserHandler = updateUserHandler {
            try await updateUserHandler(name, profileImageURL, bio, location, birthday, hasCompletedSetup)
        }
    }

    private(set) var refreshTokenCallCount = 0
    var refreshTokenHandler: (() async throws -> Void)?
    func refreshToken() async throws {
        refreshTokenCallCount += 1
        if let refreshTokenHandler = refreshTokenHandler {
            try await refreshTokenHandler()
        }
    }

    private(set) var fetchCurrentUserCallCount = 0
    var fetchCurrentUserHandler: (() async throws -> Void)?
    func fetchCurrentUser() async throws {
        fetchCurrentUserCallCount += 1
        if let fetchCurrentUserHandler = fetchCurrentUserHandler {
            try await fetchCurrentUserHandler()
        }
    }
}
