version = 0.1
[default.deploy.parameters]
stack_name = "kumatomo-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# S3 bucket for deployment artifacts (created automatically by SAM)
# s3_bucket = ""
