# =============================================================================
# SSM Parameter Store (Free tier - no Secrets Manager)
# =============================================================================

# -----------------------------------------------------------------------------
# Database Parameters
# -----------------------------------------------------------------------------
resource "aws_ssm_parameter" "db_host" {
  name        = "/${var.project_name}/${var.environment}/db_host"
  description = "RDS MySQL hostname"
  type        = "String"
  value       = aws_db_instance.main.address

  tags = {
    Name = "${var.project_name}-db-host"
  }
}

resource "aws_ssm_parameter" "db_port" {
  name        = "/${var.project_name}/${var.environment}/db_port"
  description = "RDS MySQL port"
  type        = "String"
  value       = "3306"

  tags = {
    Name = "${var.project_name}-db-port"
  }
}

resource "aws_ssm_parameter" "db_name" {
  name        = "/${var.project_name}/${var.environment}/db_name"
  description = "Database name"
  type        = "String"
  value       = var.db_name

  tags = {
    Name = "${var.project_name}-db-name"
  }
}

resource "aws_ssm_parameter" "db_username" {
  name        = "/${var.project_name}/${var.environment}/db_username"
  description = "Database username"
  type        = "String"
  value       = var.db_username

  tags = {
    Name = "${var.project_name}-db-username"
  }
}

resource "aws_ssm_parameter" "db_password" {
  name        = "/${var.project_name}/${var.environment}/db_password"
  description = "Database password"
  type        = "SecureString"
  value       = var.db_password

  tags = {
    Name = "${var.project_name}-db-password"
  }
}

# -----------------------------------------------------------------------------
# Application Parameters (to be set manually or via CI)
# -----------------------------------------------------------------------------
# APP_KEY will be generated by: php artisan key:generate --show
# Then set via: aws ssm put-parameter --name "/kumatomo/prod/app_key" --value "base64:..." --type SecureString

# Placeholder for documentation
resource "aws_ssm_parameter" "app_env" {
  name        = "/${var.project_name}/${var.environment}/app_env"
  description = "Laravel APP_ENV"
  type        = "String"
  value       = "production"

  tags = {
    Name = "${var.project_name}-app-env"
  }
}

# -----------------------------------------------------------------------------
# S3 Parameters
# -----------------------------------------------------------------------------
resource "aws_ssm_parameter" "s3_media_bucket" {
  name        = "/${var.project_name}/${var.environment}/s3_media_bucket"
  description = "S3 media bucket name"
  type        = "String"
  value       = aws_s3_bucket.media.id

  tags = {
    Name = "${var.project_name}-s3-media-bucket"
  }
}

resource "aws_ssm_parameter" "aws_region" {
  name        = "/${var.project_name}/${var.environment}/aws_region"
  description = "AWS region"
  type        = "String"
  value       = var.aws_region

  tags = {
    Name = "${var.project_name}-aws-region"
  }
}

# -----------------------------------------------------------------------------
# CloudFront Parameters (for GitHub Actions)
# -----------------------------------------------------------------------------
resource "aws_ssm_parameter" "cloudfront_distribution_id" {
  name        = "/${var.project_name}/${var.environment}/cloudfront_distribution_id"
  description = "CloudFront distribution ID"
  type        = "String"
  value       = aws_cloudfront_distribution.main.id

  tags = {
    Name = "${var.project_name}-cloudfront-distribution-id"
  }
}
